version: '3'
services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password

  backend:
    build: ./backend
    ports:
      - "8000:8888"
    environment:
      DATABASE_URL: postgres://todo_user:todo_password@database:5432/todo_db

  frontend:
    build: ./frontend
    environment:
      BACKEND_URL: http://api:8000